version: '3'
 
services:
  postgresserver:
     image: postgres
     restart: always
     ports:
       - 5432:5432
     environment:
         POSTGRES_PASSWORD: mysecretpassword
     volumes:
       - pg_data_prod:/var/lib/postgredata
     networks:
       - network
 
  gradebooksvc:
     image: denhaidash/gradebooksvc
     ports:
       - 8090:80
     environment:
       ASPNETCORE_ENVIRONMENT: Production
     links:
       - postgresserver
     depends_on:
       - "postgresserver"
     networks:
       - network
 
volumes:
  pg_data_prod:
 
networks:
  network:
     driver: bridge